#!/bin/bash
# Restore the last backedup version of the CoGs Database
#
# For use on the live webserverver.
#
# Stops the uswsgi service
# Closes all database connections
# Renames the database to a format of CoGs_timestamp
# Creates a new empty database ready to receive a restore from pgadmin4
#
# After restoring with pgadmin4 will need to:
#
# 1) Consider publishing code base if needed
# 2) Restart the uwsgi service (sudo service uwsgi start)
#
# This produces a lot of messy tracing/diagnostic output for now. 
 
# Stop the uwsgi service (which is talking to the CoGS database
# Will need to restart it again manually after a database restore
sudo service uwsgi stop

# Disconnect the processes using the CoGS database
echo "Disconnecting users..."
sudo -u postgres psql -qc "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE datname = 'CoGs';" > /dev/null 

# Define a suffix for old CoGs Database
suffix=$(date +%s)

# Rename CoGs to CoGs_timestamp
echo "Renaming database CoGs to CoGs_$suffix..."
sudo -u postgres psql -c "ALTER DATABASE \"CoGs\" RENAME TO \"CoGs_$suffix\";"

# Recreate CoGs Database 
echo "Recreating (empty) CoGs database..."
sudo -u postgres psql -c "CREATE DATABASE \"CoGs\" OWNER 'CoGs';"
