#!/bin/bash
PS4='+ ${BASH_SOURCE}:${LINENO}:${FUNCNAME[0]}: '
##############################################################################################################################
# A script support tool that simply prints a absh compatible list of database variable defintions.
##############################################################################################################################

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"

$script_dir/manage db_connection_vars
