# Generated by Django 4.0.3 on 2022-11-14 09:20

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension, TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        # Need SUPERUSER role to install these so best done by hand really as manage.py doesn't run as a SUPERUSER
        # CreateExtension('fuzzystrmatch'),
        # TrigramExtension()
    ]
