# Generated by Django 4.0.3 on 2023-02-24 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Import', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='filename',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='importcontext',
            name='editors',
            field=models.ManyToManyField(related_name='import_contexts', to=settings.AUTH_USER_MODEL, verbose_name='Editors'),
        ),
    ]
