# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='trueskill_mu0',
            field=models.FloatField(default=25.0, editable=False, verbose_name='Trueskill Initial Mean (µ)'),
        ),
        migrations.AddField(
            model_name='rating',
            name='trueskill_sigma0',
            field=models.FloatField(default=8.333333333333334, editable=False, verbose_name='Trueskill Initial Standard Deviation (σ)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 11, 15, 25, 10, 643571, tzinfo=utc)),
        ),
    ]
