# Generated by Django 2.0.3 on 2018-04-11 03:48

import bitfield.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_league_of', to='Leaderboards.League', verbose_name='Preferred League')
        ),        
        migrations.AddField(
            model_name='player',
            name='visibility_name_nickname',
            field=bitfield.models.BitField((('all', 'Everyone'), ('share_leagues', 'League Members'), ('share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), blank=True, default=0, verbose_name='Nickname Visibility')
        ),        
        migrations.AddField(
            model_name='player',
            name='visibility_name_personal',
            field=bitfield.models.BitField((('all', 'Everyone'), ('share_leagues', 'League Members'), ('share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), blank=True, default=0, verbose_name='Personal Name Visibility')
        ),        
        migrations.AddField(
            model_name='player',
            name='visibility_name_family',
            field=bitfield.models.BitField((('all', 'Everyone'), ('share_leagues', 'League Members'), ('share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), blank=True, default=0, verbose_name='Family Name Visibility')
        ),        
        migrations.AddField(
            model_name='player',
            name='visibility_email_address',
            field=bitfield.models.BitField((('all', 'Everyone'), ('share_leagues', 'League Members'), ('share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), blank=True, default=0, verbose_name='Email Address Visibility')
        ),        
        migrations.AddField(
            model_name='player',
            name='visibility_BGGname',
            field=bitfield.models.BitField((('all', 'Everyone'), ('share_leagues', 'League Members'), ('share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), blank=True, default=0, verbose_name='BoardGameGeek Name Visibility')
        ),        
    ]