# Generated by Django 2.1.1 on 2019-02-12 11:37

import bitfield.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup_rating',
            name='created_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AddField(
            model_name='backup_rating',
            name='last_edited_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AddField(
            model_name='backup_rating',
            name='last_play_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Last Play, Timezone'),
        ),
        migrations.AddField(
            model_name='backup_rating',
            name='last_victory_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Last Victory, Timezone'),
        ),
        migrations.AddField(
            model_name='game',
            name='created_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AddField(
            model_name='game',
            name='last_edited_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AddField(
            model_name='league',
            name='created_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AddField(
            model_name='league',
            name='last_edited_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AddField(
            model_name='location',
            name='last_edited_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AddField(
            model_name='location',
            name='timezone',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Timezone of the Location'),
        ),
        migrations.AddField(
            model_name='performance',
            name='created_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AddField(
            model_name='performance',
            name='last_edited_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AddField(
            model_name='player',
            name='created_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_edited_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AddField(
            model_name='rank',
            name='created_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AddField(
            model_name='rank',
            name='last_edited_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AddField(
            model_name='rating',
            name='created_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AddField(
            model_name='rating',
            name='last_edited_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AddField(
            model_name='rating',
            name='last_play_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Last Play, Timezone'),
        ),
        migrations.AddField(
            model_name='rating',
            name='last_victory_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Last Victory, Timezone'),
        ),
        migrations.AddField(
            model_name='rebuild_log',
            name='date_time_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Ratings Rebuild, Timezone'),
        ),
        migrations.AddField(
            model_name='session',
            name='created_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AddField(
            model_name='session',
            name='date_time_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Timezone'),
        ),
        migrations.AddField(
            model_name='session',
            name='last_edited_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AddField(
            model_name='team',
            name='created_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AddField(
            model_name='team',
            name='last_edited_on_tz',
            field=models.CharField(default='Australia/Hobart', max_length=64, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AlterField(
            model_name='backup_rating',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_ratings_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='backup_rating',
            name='created_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Creation'),
        ),
        migrations.AlterField(
            model_name='backup_rating',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_ratings', to='Leaderboards.Game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='backup_rating',
            name='last_edited_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_ratings_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
        migrations.AlterField(
            model_name='backup_rating',
            name='last_edited_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Last Edit'),
        ),
        migrations.AlterField(
            model_name='backup_rating',
            name='last_play',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), verbose_name='Time of Last Play'),
        ),
        migrations.AlterField(
            model_name='backup_rating',
            name='last_victory',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), verbose_name='Time of Last Victory'),
        ),
        migrations.AlterField(
            model_name='backup_rating',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_ratings', to='Leaderboards.Player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Creation'),
        ),
        migrations.AlterField(
            model_name='game',
            name='individual_play',
            field=models.BooleanField(default=True, verbose_name='Supports individual play'),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_edited_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_edited_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Last Edit'),
        ),
        migrations.AlterField(
            model_name='game',
            name='leagues',
            field=models.ManyToManyField(blank=True, related_name='games_played', to='Leaderboards.League', verbose_name='Leagues'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_play',
            field=models.BooleanField(default=False, verbose_name='Supports team play'),
        ),
        migrations.AlterField(
            model_name='league',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='league',
            name='created_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Creation'),
        ),
        migrations.AlterField(
            model_name='league',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='played_by_leagues', to='Leaderboards.Game', verbose_name='Games'),
        ),
        migrations.AlterField(
            model_name='league',
            name='last_edited_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
        migrations.AlterField(
            model_name='league',
            name='last_edited_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Last Edit'),
        ),
        migrations.AlterField(
            model_name='league',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='leagues_playing_here', to='Leaderboards.Location', verbose_name='Locations'),
        ),
        migrations.AlterField(
            model_name='league',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leagues_managed', to='Leaderboards.Player', verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='league',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='member_of_leagues', to='Leaderboards.Player', verbose_name='Players'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Creation'),
        ),
        migrations.AlterField(
            model_name='location',
            name='last_edited_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
        migrations.AlterField(
            model_name='location',
            name='last_edited_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Last Edit'),
        ),
        migrations.AlterField(
            model_name='location',
            name='leagues',
            field=models.ManyToManyField(blank=True, related_name='Locations_used', to='Leaderboards.League', verbose_name='Leagues using the Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name of the Location'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='created_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Creation'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='last_edited_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='last_edited_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Last Edit'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='Leaderboards.Player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='Leaderboards.Session', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='player',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='player',
            name='created_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Creation'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_edited_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_edited_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Last Edit'),
        ),
        migrations.AlterField(
            model_name='player',
            name='leagues',
            field=models.ManyToManyField(blank=True, related_name='players_in_league', to='Leaderboards.League', verbose_name='Leagues'),
        ),
        migrations.AlterField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(editable=False, related_name='players_in_team', to='Leaderboards.Team', verbose_name='Teams'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='player',
            name='visibility_BGGname',
            field=bitfield.models.BitField((('all', 'Everyone'), ('share_leagues', 'League Members'), ('share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), blank=True, default=6, verbose_name='BoardGameGeek Name Visibility'),
        ),
        migrations.AlterField(
            model_name='player',
            name='visibility_email_address',
            field=bitfield.models.BitField((('all', 'Everyone'), ('share_leagues', 'League Members'), ('share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), blank=True, default=6, verbose_name='Email Address Visibility'),
        ),
        migrations.AlterField(
            model_name='player',
            name='visibility_name_family',
            field=bitfield.models.BitField((('all', 'Everyone'), ('share_leagues', 'League Members'), ('share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), blank=True, default=2, verbose_name='Family Name Visibility'),
        ),
        migrations.AlterField(
            model_name='player',
            name='visibility_name_nickname',
            field=bitfield.models.BitField((('all', 'Everyone'), ('share_leagues', 'League Members'), ('share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), blank=True, default=1, verbose_name='Nickname Visibility'),
        ),
        migrations.AlterField(
            model_name='player',
            name='visibility_name_personal',
            field=bitfield.models.BitField((('all', 'Everyone'), ('share_leagues', 'League Members'), ('share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), blank=True, default=1, verbose_name='Personal Name Visibility'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranks_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='created_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Creation'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='last_edited_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranks_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='last_edited_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Last Edit'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranks', to='Leaderboards.Player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.PositiveIntegerField(verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='Leaderboards.Session', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='team',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranks', to='Leaderboards.Team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Creation'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Leaderboards.Game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='last_edited_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='last_edited_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Last Edit'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='last_play',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), verbose_name='Time of Last Play'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='last_victory',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), verbose_name='Time of Last Victory'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Leaderboards.Player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='rebuild_log',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of Ratings Rebuild'),
        ),
        migrations.AlterField(
            model_name='rebuild_log',
            name='duration',
            field=models.DurationField(verbose_name='Duration of Rebuild'),
        ),
        migrations.AlterField(
            model_name='rebuild_log',
            name='ratings',
            field=models.PositiveIntegerField(verbose_name='Number of Ratings Built'),
        ),
        migrations.AlterField(
            model_name='rebuild_log',
            name='reason',
            field=models.TextField(verbose_name='Reason for Rebuild'),
        ),
        migrations.AlterField(
            model_name='rebuild_log',
            name='rebuilt_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_rebuilds', to=settings.AUTH_USER_MODEL, verbose_name='Rebuilt By'),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Creation'),
        ),
        migrations.AlterField(
            model_name='session',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='Leaderboards.Game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='session',
            name='last_edited_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
        migrations.AlterField(
            model_name='session',
            name='last_edited_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Last Edit'),
        ),
        migrations.AlterField(
            model_name='session',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='Leaderboards.League', verbose_name='League'),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='Leaderboards.Location', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='team_play',
            field=models.BooleanField(default=False, verbose_name='Team Play'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Creation'),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_edited_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_edited_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Time of Last Edit'),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, editable=False, related_name='member_of_teams', to='Leaderboards.Player', verbose_name='Players'),
        ),
    ]
