# Generated by Django 2.1.7 on 2019-02-12 12:21

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0002_auto_20190212_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_rating',
            name='created_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AlterField(
            model_name='backup_rating',
            name='last_edited_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AlterField(
            model_name='backup_rating',
            name='last_play_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Last Play, Timezone'),
        ),
        migrations.AlterField(
            model_name='backup_rating',
            name='last_victory_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Last Victory, Timezone'),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_edited_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AlterField(
            model_name='league',
            name='created_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AlterField(
            model_name='league',
            name='last_edited_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AlterField(
            model_name='location',
            name='last_edited_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AlterField(
            model_name='location',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', verbose_name='Timezone of the Location'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='created_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='last_edited_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AlterField(
            model_name='player',
            name='created_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_edited_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='created_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='last_edited_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='last_edited_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='last_play_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Last Play, Timezone'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='last_victory_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Last Victory, Timezone'),
        ),
        migrations.AlterField(
            model_name='rebuild_log',
            name='date_time_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Ratings Rebuild, Timezone'),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_time_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='session',
            name='last_edited_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Last Edit, Timezone'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Creation, Timezone'),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_edited_on_tz',
            field=timezone_field.fields.TimeZoneField(default='Australia/Hobart', editable=False, verbose_name='Time of Last Edit, Timezone'),
        ),
    ]
