# Generated by Django 2.1.1 on 2018-11-15 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0002_auto_20180411_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup_rating',
            options={'get_latest_by': 'created_on', 'ordering': ['-trueskill_eta']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'get_latest_by': 'created_on', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'get_latest_by': 'created_on', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'get_latest_by': 'created_on', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'get_latest_by': 'created_on', 'ordering': ['session', 'player']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'get_latest_by': 'created_on', 'ordering': ['name_nickname']},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'get_latest_by': 'created_on', 'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'get_latest_by': 'created_on', 'ordering': ['-trueskill_eta']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'get_latest_by': 'created_on', 'ordering': ['-date_time']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'get_latest_by': 'created_on'},
        ),
        migrations.AlterField(
            model_name='game',
            name='max_players_per_team',
            field=models.PositiveIntegerField(default=4, verbose_name='Maximum number of players in a team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_players_per_team',
            field=models.PositiveIntegerField(default=2, verbose_name='Minimum number of players in a team'),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='reserved', inverse_match=True, message='GLOBAL is a reserved league name', regex='^GLOBAL$')], verbose_name='Name of the League'),
        ),
    ]
