# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0002_auto_20161011_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-trueskill_eta']},
        ),
        migrations.AddField(
            model_name='performance',
            name='play_number',
            field=models.PositiveIntegerField(default=1, verbose_name='The number of this play (for this player at this game)'),
        ),
        migrations.AddField(
            model_name='rating',
            name='plays',
            field=models.PositiveIntegerField(default=0, verbose_name='Play Count'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
