# Generated by Django 4.0.3 on 2023-02-26 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Import', '0003_alter_import_filename_alter_importcontext_editors'),
        ('Leaderboards', '0003_session_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='Import.import', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='location',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='Import.import', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='player',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='Import.import', verbose_name='Source'),
        ),
    ]
