# Generated by Django 2.1.7 on 2019-02-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0003_auto_20190212_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trueskillsettings',
            name='beta',
        ),
        migrations.AddField(
            model_name='game',
            name='trueskill_beta',
            field=models.FloatField(default=4.166666666666667, verbose_name='TrueSkill Skill Factor (ß)'),
        ),
    ]
