# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0003_auto_20161017_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='trueskill_beta',
            field=models.FloatField(default=4.166666666666667, verbose_name='TrueSkill Skill Factor (ß)'),
        ),
        migrations.AddField(
            model_name='rating',
            name='trueskill_delta',
            field=models.FloatField(default=0.0001, verbose_name='TrueSkill Delta (δ)'),
        ),
        migrations.AddField(
            model_name='rating',
            name='trueskill_p',
            field=models.FloatField(default=0.1, verbose_name='TrueSkill Draw Probability (p)'),
        ),
        migrations.AddField(
            model_name='rating',
            name='trueskill_tau',
            field=models.FloatField(default=0.08333333333333334, verbose_name='TrueSkill Dynamics Factor (τ)'),
        ),
    ]
