# Generated by Django 4.0.3 on 2023-02-26 07:02

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0004_game_source_location_source_player_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notes',
            field=markdownfield.models.MarkdownField(null=True, rendered_field='notes_rendered'),
        ),
        migrations.AddField(
            model_name='event',
            name='notes_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='notes',
            field=markdownfield.models.MarkdownField(null=True, rendered_field='notes_rendered'),
        ),
        migrations.AddField(
            model_name='game',
            name='notes_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='notes',
            field=markdownfield.models.MarkdownField(null=True, rendered_field='notes_rendered'),
        ),
        migrations.AddField(
            model_name='league',
            name='notes_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='notes',
            field=markdownfield.models.MarkdownField(null=True, rendered_field='notes_rendered'),
        ),
        migrations.AddField(
            model_name='player',
            name='notes_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='notes',
            field=markdownfield.models.MarkdownField(null=True, rendered_field='notes_rendered'),
        ),
        migrations.AddField(
            model_name='session',
            name='notes_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='notes',
            field=markdownfield.models.MarkdownField(null=True, rendered_field='notes_rendered'),
        ),
        migrations.AddField(
            model_name='team',
            name='notes_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AddField(
            model_name='tourney',
            name='notes',
            field=markdownfield.models.MarkdownField(null=True, rendered_field='notes_rendered'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='notes_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
    ]
