# Generated by Django 2.1.1 on 2019-04-22 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0004_auto_20190212_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='Leaderboards.Location', verbose_name='Location'),
        ),
    ]
