# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0004_auto_20161017_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='individual_play',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='team_play',
            field=models.BooleanField(default=False),
        ),
    ]
