# Generated by Django 4.1.4 on 2023-03-01 00:28

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0005_event_notes_event_notes_rendered_game_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='notes',
            field=markdownfield.models.MarkdownField(null=True, rendered_field='notes_rendered'),
        ),
        migrations.AddField(
            model_name='location',
            name='notes_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
    ]
