# Generated by Django 4.1.4 on 2023-03-10 10:25

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0006_location_notes_location_notes_rendered'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='visibility_location',
            field=bitfield.models.BitField((('all', 'Everyone'), ('share_leagues', 'League Members'), ('share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), blank=True, default=1, verbose_name='Geolocation Visibility'),
        ),
    ]
