# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0007_auto_20161020_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_players_per_team',
            field=models.PositiveIntegerField(default=0, verbose_name='Maximum number of players in a team'),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players_per_team',
            field=models.PositiveIntegerField(default=0, verbose_name='Minimum number of players in a team'),
        ),
    ]
