# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0008_auto_20161021_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='victories',
            field=models.PositiveIntegerField(default=0, verbose_name='Victory Count'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='play_number',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='The number of this play (for this player at this game)'),
        ),
    ]
