# Generated by Django 4.1.4 on 2023-03-15 09:55

from django.db import migrations, models
import django.db.models.deletion
import django_rich_views.serializers


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0008_location_blur_radius_alter_event_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard_Cache',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='leaderboard_cache', serialize=False, to='Leaderboards.session', verbose_name='Session')),
                ('board', models.JSONField(decoder=django_rich_views.serializers.TypedDecoder, encoder=django_rich_views.serializers.TypedEncoder, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='blur_radius',
            field=models.FloatField(blank=True, null=True, verbose_name='Radius of Uncertainy for Hidden Locations'),
        ),
    ]
