# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0009_auto_20161105_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='victory_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='The count of victories after this session (for this player at this game)'),
        ),
    ]
