# Generated by Django 4.2 on 2023-04-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Import', '0003_alter_import_filename_alter_importcontext_editors'),
        ('Leaderboards', '0011_alter_game_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='source',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='Import.import', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tourneys',
            field=models.ManyToManyField(blank=True, editable=False, through='Leaderboards.TourneyRules', to='Leaderboards.tourney', verbose_name='Tourneys'),
        ),
        migrations.AlterField(
            model_name='player',
            name='source',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='Import.import', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='session',
            name='source',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='Import.import', verbose_name='Source'),
        ),
    ]
