# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 12:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Leaderboards', '0011_auto_20170114_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plays', models.PositiveIntegerField(default=0, verbose_name='Play Count')),
                ('victories', models.PositiveIntegerField(default=0, verbose_name='Victory Count')),
                ('last_play', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_victory', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('trueskill_mu', models.FloatField(default=25.0, editable=False, verbose_name='Trueskill Mean (µ)')),
                ('trueskill_sigma', models.FloatField(default=8.333333333333334, editable=False, verbose_name='Trueskill Standard Deviation (σ)')),
                ('trueskill_eta', models.FloatField(default=8.333333333333334, editable=False, verbose_name='Trueskill Rating (η)')),
                ('trueskill_mu0', models.FloatField(default=25.0, editable=False, verbose_name='Trueskill Initial Mean (µ)')),
                ('trueskill_sigma0', models.FloatField(default=8.333333333333334, editable=False, verbose_name='Trueskill Initial Standard Deviation (σ)')),
                ('trueskill_beta', models.FloatField(default=4.166666666666667, verbose_name='TrueSkill Skill Factor (ß)')),
                ('trueskill_delta', models.FloatField(default=0.0001, verbose_name='TrueSkill Delta (δ)')),
                ('trueskill_tau', models.FloatField(default=0.08333333333333334, verbose_name='TrueSkill Dynamics Factor (τ)')),
                ('trueskill_p', models.FloatField(default=0.1, verbose_name='TrueSkill Draw Probability (p)')),
                ('created_on', models.DateTimeField(editable=False, null=True)),
                ('last_edited_on', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['-trueskill_eta'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='last_victory',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='backup_rating',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_ratings_created', to='Leaderboards.Player'),
        ),
        migrations.AddField(
            model_name='backup_rating',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_ratings', to='Leaderboards.Game'),
        ),
        migrations.AddField(
            model_name='backup_rating',
            name='last_edited_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_ratings_last_edited', to='Leaderboards.Player'),
        ),
        migrations.AddField(
            model_name='backup_rating',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_ratings', to='Leaderboards.Player'),
        ),
    ]
