# Generated by Django 5.1.6 on 2025-04-08 04:06

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0012_alter_game_source_alter_game_tourneys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=markdownfield.models.MarkdownField(blank=True, default='', null=True, rendered_field='notes_rendered'),
        ),
        migrations.AlterField(
            model_name='game',
            name='notes',
            field=markdownfield.models.MarkdownField(blank=True, default='', null=True, rendered_field='notes_rendered'),
        ),
        migrations.AlterField(
            model_name='league',
            name='notes',
            field=markdownfield.models.MarkdownField(blank=True, default='', null=True, rendered_field='notes_rendered'),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=markdownfield.models.MarkdownField(blank=True, default='', null=True, rendered_field='notes_rendered'),
        ),
        migrations.AlterField(
            model_name='player',
            name='notes',
            field=markdownfield.models.MarkdownField(blank=True, default='', null=True, rendered_field='notes_rendered'),
        ),
        migrations.AlterField(
            model_name='session',
            name='notes',
            field=markdownfield.models.MarkdownField(blank=True, default='', null=True, rendered_field='notes_rendered'),
        ),
        migrations.AlterField(
            model_name='team',
            name='notes',
            field=markdownfield.models.MarkdownField(blank=True, default='', null=True, rendered_field='notes_rendered'),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='notes',
            field=markdownfield.models.MarkdownField(blank=True, default='', null=True, rendered_field='notes_rendered'),
        ),
    ]
