# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0012_auto_20170119_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rebuild_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ratings', models.PositiveIntegerField()),
                ('duration', models.DurationField()),
                ('reason', models.TextField(verbose_name='Reason')),
                ('rebuilt_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_rebuilds', to='Leaderboards.Player')),
            ],
        ),
    ]
