# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0013_rebuild_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.AlterField(
            model_name='performance',
            name='trueskill_beta',
            field=models.FloatField(default=4.166666666666667, editable=False, verbose_name='TrueSkill Skill Factor (ß)'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='trueskill_delta',
            field=models.FloatField(default=0.0001, editable=False, verbose_name='TrueSkill Delta (δ)'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='trueskill_p',
            field=models.FloatField(default=0.1, editable=False, verbose_name='TrueSkill Draw Probability (p)'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='trueskill_tau',
            field=models.FloatField(default=0.08333333333333334, editable=False, verbose_name='TrueSkill Dynamics Factor (τ)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='BGGname',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='BoardGameGeek Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(editable=False, related_name='players_in_team', to='Leaderboards.Team'),
        ),
    ]
