# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-04 02:14
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0015_player_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['session', 'player']},
        ),
        migrations.AlterField(
            model_name='player',
            name='visibility_BGGname',
            field=bitfield.models.BitField((('all', 'Everyone'), ('all_share_leagues', 'League Members'), ('all_share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), default=0, verbose_name='BoardGameGeek Name Visibility'),
        ),
        migrations.AlterField(
            model_name='player',
            name='visibility_email_address',
            field=bitfield.models.BitField((('all', 'Everyone'), ('all_share_leagues', 'League Members'), ('all_share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), default=0, verbose_name='Email Address Visibility'),
        ),
        migrations.AlterField(
            model_name='player',
            name='visibility_name_family',
            field=bitfield.models.BitField((('all', 'Everyone'), ('all_share_leagues', 'League Members'), ('all_share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), default=0, verbose_name='Family Name Visibility'),
        ),
        migrations.AlterField(
            model_name='player',
            name='visibility_name_nickname',
            field=bitfield.models.BitField((('all', 'Everyone'), ('all_share_leagues', 'League Members'), ('all_share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), default=0, verbose_name='Nickname Visibility'),
        ),
        migrations.AlterField(
            model_name='player',
            name='visibility_name_personal',
            field=bitfield.models.BitField((('all', 'Everyone'), ('all_share_leagues', 'League Members'), ('all_share_teams', 'Team Members'), ('all_is_registrar', 'Registrars'), ('all_is_staff', 'Staff')), default=0, verbose_name='Personal Name Visibility'),
        ),
    ]
